### ISSUE TITLE
Inconsistent base64 return values

### ISSUE THREAD

**Issue by michaelschneiderdaimler** [cesarvr/pdf-generator#113]
Hi, 

we're using your plugin in an iOS app. 
We observed that if pass the same input to the plugin several times, we get different result base64 strings. The generated PDF looks consistent, but we are wondering what the cause for this behaviour could be. 
We want to generate some critical packaging labels, so we need to be sure that the plugin behaves somewhat consistently - any idea what is going on? I didn't find anything by digging through the code...
Input: 
`pdf.fromData('<style type="text/css">.clara {color: blue; font-weight: lighter; font-family: Arial, Helvetica}</style><html><div class="clara">Hello from Stuttgart!</div><div>Hallo aus Deutschland ... </div></html>', { documentSize: 'A4', type: 'base64'}).then(function(res) { console.log(res) })`

Result:
[pdf-result-1.txt](https://github.com/cesarvr/pdf-generator/files/4318557/pdf-result-1.txt)
[pdf-result-2.txt](https://github.com/cesarvr/pdf-generator/files/4318558/pdf-result-2.txt)

**Comment by cesarvr** [comment]
Hey @michaelschneiderdaimler , 

It's going to be difficult to achieve accuracy at byte level between the same PDF, because the PDF API (used by the browser behind the scenes) adds arbitrary metadata values (like dates, prefixes, etc) in the [PDF script](https://en.wikipedia.org/wiki/PostScript) code that internally defines the final document. If you transform this base64 into a PDF script you will find that objects in the [PDF script](https://en.wikipedia.org/wiki/PostScript) are not even (sometimes) defined in the same order, which explains the difference in Base64 results.

On the other hand the visual accuracy will be there because that's the purpose of PDF technology.

Example:

Block of text defined internally in different order with arbitrary prefixes:

<img width="1416" alt="Screenshot 2020-03-15 at 13 24 31" src="https://user-images.githubusercontent.com/3899337/76702257-64da3f00-66c0-11ea-98df-0fdcf3753b78.png">

Visual representation of the files:

<img width="267" alt="Screenshot 2020-03-15 at 13 26 59" src="https://user-images.githubusercontent.com/3899337/76702333-e6ca6800-66c0-11ea-90ec-e5c49db77cff.png">
<img width="509" alt="Screenshot 2020-03-15 at 13 27 16" src="https://user-images.githubusercontent.com/3899337/76702335-e9c55880-66c0-11ea-88e9-a5e6d56f2794.png">


Hope it helps.

**Comment by michaelschneiderdaimler** [comment]
Hi Cesar,
many thanks for the explanation! 
We were already suspecting that some dynamic stuff was inserted in the PDF, but since I found no such code neither in the plugin nor in the native code, I was wondering where that happened.

I'm closing the isse.

Best regards
michael
