### ISSUE TITLE
reduce quality of pdf

### ISSUE THREAD

**Issue by mnewmedia** [cesarvr/pdf-generator#25]
I use the it to generate the invoice as a pdf. But since my images are high quality the pdf gets with around 10 items a size of 20mb. So I need to find a way to reduce the overall quality of the pdf, or the quality of the images before they are added to the pdf.

May this can help
- [stackoverflow ipad-retina-display..](http://stackoverflow.com/questions/16127974/ipad-retina-display-is-there-a-way-to-reduce-filesize-of-pdf-created-with-cgcont)

**Comment by cesarvr** [comment]
The objective of the plugin is to be [WYSIWYG](https://en.wikipedia.org/wiki/WYSIWYG), you can control everything in the pre-render stage by scaling down the images, take a look at [this](http://stackoverflow.com/questions/18922880/html5-canvas-resize-downscale-image-high-quality), and then pass this to the pdf-generator.

**Comment by mnewmedia** [comment]
Before this plugin I used [pdfmake](pdfmake.org) and there I already did the js downscaling. But scaling 40 Hi-Res images down on an iPad-Air 2 took around 30 seconds and on some older iPhones even crash. 
I tried a lot solutions and you Plugin is the best so far, because it's native, fast and needs almost no memory. So I would like to keep going the native way.

WYSIGYG is a great objective, but if you provide an options to reduce the quality/filesize, it's still WYSIWYG. Now I will continue to try finding a way to add this to BNHtmlPdfKit and then to your plugin.

**Comment by cesarvr** [comment]
I think that if you try to do it in BNHtmlPdfKit will be more difficult because that API is using Webkit to transform all the HTML Document to PDF and in the process Webkit act just as a browser he get assets and renders it using some guidelines (HTML/CSS), when finish those assets add up to the total amount of your file (20mb), so If I was you i will try to attack those heavy assets (images) individually by compression/downscaling so the effort will be more effective.

**Comment by mnewmedia** [comment]
I already attacked the images with all power I had and the result was not satisfying =)
So I will keep googling native solutions for today.

**Comment by mnewmedia** [comment]
Thank you anyway! =)
