### ISSUE TITLE
pdf variable undefined error

### ISSUE THREAD

**Issue by attigo2010** [cesarvr/pdf-generator#67]
Hello, 

I am trying to use this plugin, but I am getting error pdf variable undefined. 
Could you please help me realize where the global pdf variable is defined. 
Am I missing something, how do you think?

Thank you very much in advance!
Kind regards!

**Comment by cesarvr** [comment]
Umm I think the problem is that the plugin didn't get installed, can you try the following: 

`cordova plugins`  

You should see the plugin, if you don't:  Try reinstall the plugin you can follow this [directions](https://www.npmjs.com/package/cordova-pdf-generator). 

If you see it, then that means that the plugin didn't make it to the .APK  (Android Executable)  or .IPA (iOS Executable). 

Try, delete your platform folder: 

`rm -r platform` 

Then 
`cordova platform add android ios` , This command will create the two projects (Android, iOS) and will try to load the plugins, keep an eye in the logs if some error happens. 

Cheers.

**Comment by attigo2010** [comment]
Thank you very much! For some reason, it wasn't installed. :)
