### ISSUE TITLE
how to restrict number of pages

### ISSUE THREAD

**Issue by Chousse** [cesarvr/pdf-generator#90]
Hi,
When I generate a pdf file fromData with payload("some HTML") I have more than 17 pages (16 blanks) but my HTML fit normally in a A4 document.
Is it possible de restraint the number of pages ?
Thanks

**Comment by cesarvr** [comment]
This can happen because there is a big margin or padding at the bottom of the HTML after rendering. I think you should try to preview the HTML in your browser first and try to see if you can spot some anomalies at the bottom of the final document. 

Here is a [working example](https://github.com/cesarvr/pdf-generator-example). 

Cheers 👍.
